### PR TITLE
Add sjors attestations for v23.0.knots20220529

### PR DESCRIPTION
**Pull request by Sjors**

### CODE REVIEW

**Comment by Sjors** [comment]
This went better than #4, but it still shows a difference with @achow101 and others:

```
< 0dfa15fb9f29142b781780ef7c80c8a4f8fe67fd6157428c822414bf8c23d371  bitcoin-23.0.knots20220529.tar.gz
---
> d1770c2bf1f9713086f34e8429a3b99a6b31e850b491bacb7d683222f722d430  bitcoin-23.0.knots20220529.tar.gz
ERR: The SHA256SUMS attestation in these two directories differ:
    '../knots-guix.sigs/23.0.knots20220529/sjors/noncodesigned.SHA256SUMS'
    '../knots-guix.sigs/23.0.knots20220529/achow101/noncodesigned.SHA256SUMS'
```

**Comment by achow101** [comment]
Solution for that: https://github.com/bitcoinknots/guix.sigs/pull/3#issuecomment-1375902239

**Comment by Sjors** [comment]
That worked. I pushed a second commit with the change.

**Review by salasjuarezederaldair60-eng — COMMENTED** [review]
añadir testigos

**Pull request merged**
