### PR TITLE
Update achow101 attestation for 23.0.knots20220529 corrected source tarball

### PR DESCRIPTION
**Pull request by achow101**
Rebuilt with a modified build script.

### CODE REVIEW

**Comment by luke-jr** [comment]
Can you share how you built it, for others?

**Comment by achow101** [comment]
I made a copy of `contrib/guix/guix-build` and applied the following diff:

```diff
diff --git a/contrib/guix/guix-build b/contrib/guix/guix-build
index fccea517e8..3e0b48c107 100755
--- a/contrib/guix/guix-build
+++ b/contrib/guix/guix-build
@@ -472,6 +472,7 @@ EOF
                                         DISTSRC="$(DISTSRC_BASE=/distsrc-base && distsrc_for_host "$HOST")" \
                                         OUTDIR="$(OUTDIR_BASE=/outdir-base && outdir_for_host "$HOST")" \
                                         DIST_ARCHIVE_BASE=/outdir-base/dist-archive \
+                                        ${REFERENCE_DATETIME:+REFERENCE_DATETIME="$REFERENCE_DATETIME"} \
                                       bash -c "cd /bitcoin && bash contrib/guix/libexec/build.sh"
     )
```

Then I ran it with `REFERENCE_DATETIME="2022-05-29 00:00"` set as an environment variable.

**Comment by hebasto** [comment]
@achow101 
> I made a copy of `contrib/guix/guix-build` and applied the following diff:
> 
> ```diff
> diff --git a/contrib/guix/guix-build b/contrib/guix/guix-build
> index fccea517e8..3e0b48c107 100755
> --- a/contrib/guix/guix-build
> +++ b/contrib/guix/guix-build
> @@ -472,6 +472,7 @@ EOF
>                                          DISTSRC="$(DISTSRC_BASE=/distsrc-base && distsrc_for_host "$HOST")" \
>                                          OUTDIR="$(OUTDIR_BASE=/outdir-base && outdir_for_host "$HOST")" \
>                                          DIST_ARCHIVE_BASE=/outdir-base/dist-archive \
> +                                        ${REFERENCE_DATETIME:+REFERENCE_DATETIME="$REFERENCE_DATETIME"} \
>                                        bash -c "cd /bitcoin && bash contrib/guix/libexec/build.sh"
>      )
> ```
> 
> Then I ran it with `REFERENCE_DATETIME="2022-05-29 00:00"` set as an environment variable.

Does your approach implies setting the `FORCE_DIRTY_WORKTREE` environment variable?

**Comment by achow101** [comment]
> Does your approach implies setting the `FORCE_DIRTY_WORKTREE` environment variable?

No. I made a copy of `guix-build`. Since this copy isn't part of the git tree, the worktree isn't detected as being dirty.

**Pull request merged**
