### PR TITLE
Add achow101 23.0.knots20220529 non-codesigned guix attestation

### PR DESCRIPTION
**Pull request by achow101**

### CODE REVIEW

**Comment by achow101** [comment]
It appears that the source tarballs mismatch, between laanwj and luke-jr's too.

**Comment by luke-jr** [comment]
Hmm, that complicates things.

**Comment by luke-jr** [comment]
Could you compare your source tarball to [the one I presumably made months ago (**but potentially compromised**)](https://luke.dashjr.org/.RISKY/programs/bitcoin/files/bitcoin-knots/23.x/23.0.knots20220529/bitcoin-23.0.knots20220529.tar.gz)? Or perhaps more ideally to @laanwj's if he still has it around.

The issue is less about which one to publish (could just refer to git for source code), and more to do with being able to combine the signatures. I don't expect I'll be able to fix the determinism problem any time soon, but if the comparison is simple maybe the signatures can be updated to use the same hash after verifying the difference isn't an issue.

**Comment by achow101** [comment]
Looks like it's just a timestamp difference. The timestamps for the files in the tarball are different, but the contents themselves are correct. I believe this is due to `REFERENCE_DATETIME` that is not set in `contrib/guix/libexec/make_source_tarball.sh`. It should probably be "SOURCE_DATE_EPOCH" to use the timestamp that everything else does. Because of Guix's sandboxing, it's not possible to provide the correct timestamp in the build command, but I think I can still produce a source tarball with a hash that matches yours.

**Comment by laanwj** [comment]
I don't have the file around anymore, sorry.

**Pull request merged**
