### PR TITLE
Add sjors attestations for v23.0.knots20220529-0-ga5eb5c7e30

### PR DESCRIPTION
**Pull request by Sjors**
For some reason `./contrib/guix/guix-build` appended `-0-ga5eb5c7e30` to the version.

I'm also getting different hashes than @achow101 so maybe I did something wrong?

I used `git checkout v23.0.knots20220529`

### CODE REVIEW

**Comment by achow101** [comment]
I don't know why that would happen. It worked fine for me. What do you get for `git describe --exact-match`?

**Comment by Sjors** [comment]
```
$ git describe --exact-match
warning: tag 'show' is externally known as 'v23.0.knots20220529'
v23.0.knots20220529-0-ga5eb5c7e30
```

```
$ git remote -v
origin	https://github.com/bitcoinknots/bitcoin.git (fetch)
origin	https://github.com/bitcoinknots/bitcoin.git (push)
```

**Comment by achow101** [comment]
The correct output of `git describe --exact-match` should be `v23.0.knots20220529`

```
warning: tag 'show' is externally known as 'v23.0.knots20220529'
```

Did you do `git tag show` and accidentally create a tag named `show`? If you remove that tag, does that command return the expected string?

**Comment by Sjors** [comment]
Ah, oops, as I was throwing some incantations while comparing the hashes to what Wladimir found. I'll do another build.

**Pull request closed without merging**
